### ISSUE TITLE
Q: Profiles for different machines?

### ISSUE THREAD

**Issue by nmaludy** [phodge/homely#44]
I'm just starting my dotfile management journey and stumbled upon homely. I've seen in a few of the other management systems that "machine profiles" are supported to allow users to choose what config files are deployed depending on hostname/os/command-line-arg. Does homely support something like this?

**Comment by phodge** [comment]
@nmaludy: I haven't built any features to detect hostname or operating system, but that's because these are things you can already do easily in python.

See http://stackoverflow.com/questions/4271740/how-can-i-use-python-to-get-the-system-hostname and http://stackoverflow.com/questions/1854/python-what-os-am-i-running-on for examples.
